services:
  teldrive:
    image: ghcr.io/tgdrive/teldrive
    restart: always
    container_name: teldrive
    networks:
     - postgres
    volumes:
      - ./config.toml:/config.toml
      - type: bind
        source: ./session.db
        target: /session.db
    ports:
      - 8080:8080
networks:
  postgres:                                 
    external: true